name: development

on:
  push:
    branches: [ "dev" ]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show architecture
        run: make info

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test
        run: make test

      - name: Run test
        run: echo "gas\n" | ./bin/test davidgaspardev
