name: development

on:
  push:
    branches: [ "dev" ]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show architecture
        run: make info

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build library for x86_64
        run: make library ARCH=x86_64
      
      - name: Copy library to base name
        run: cp lib/libbytes_x64_64.a lib/libbytes.a

      - name: Build test
        run: make test ARCH=x86_64

      - name: Run test
        run: echo "gas\n" | ./bin/test davidgaspardev
