name: d-string

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: show architecture
        run: make info

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build test
      run: make test

    - name: run test
      run: echo "gas\n" | ./bin/test davidgaspardev
  
  lib:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v3

    - name: build lib
      run: make library
    
    - uses: actions/upload-artifact@v3
      with:
        name: libbytes
        path: lib/libbytes.a
