name: Release Page

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # For arm64-apple-darwin
      - name: Build library for arm64-apple-darwin
        run: make library CTARGET=arm64-apple-darwin
      - name: Clear build from arm64-apple-darwin
        run: make clean_build
      
      # For x86_64-apple-darwin
      - name: Build library for x86_64-apple-darwin
        run: make library CTARGET=x86_64-apple-darwin
      - name: Clear build from x86_64-apple-darwin
        run: make clean_build
      
      # For arm64-linux-gnu
      - name: Build library for arm64-linux-gnu
        run: make library CTARGET=arm64-linux-gnu
      - name: Clear build from arm64-linux-gnu
        run: make clean_build
      
      # For x86_64-linux-gnu
      - name: Build library for x86_64-linux-gnu
        run: make library CTARGET=x86_64-linux-gnu
      - name: Clear build from x86_64-linux-gnu
        run: make clean_build

      - name: Create Release Page
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload header file to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/bytes.h
          asset_name: bytes.h
          asset_content_type: text/plain
      
      - name: Upload compiled file (arm64-apple-darwin) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libbytes_arm64-apple-darwin.a
          asset_name: libbytes_arm64-apple-darwin.a
          asset_content_type: text/plain
      
      - name: Upload compiled file (x86_64-apple-darwin) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libbytes_x86_64-apple-darwin.a
          asset_name: libbytes_x86_64-apple-darwin.a
          asset_content_type: text/plain

      - name: Upload compiled file (arm64-linux-gnu) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libbytes_arm64-linux-gnu.a
          asset_name: libbytes_arm64-linux-gnu.a
          asset_content_type: text/plain

      - name: Upload compiled file (x86_64-linux-gnu) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libbytes_x86_64-linux-gnu.a
          asset_name: libbytes_x86_64-linux-gnu.a
          asset_content_type: text/plain
