name: release

on:
  pull_request:
    branches: [ "main" ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: build library
        run: make library
      
      - name: upload library
        uses: actions/upload-artifact@v3
        with:
          name: libbytes.a
          path: lib/libbytes.a