name: release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build library for arm64
        run: make library ARCH=arm64
      
      - name: Build library for x86_64
        run: make library ARCH=x86_64
           
      - name: Create Release Page
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload header file to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          asset_path: src/bytes.h
          asset_name: bytes.h
          asset_content_type: text/plain
      
      - name: Upload compiled file (arm64) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libbytes_arm64.a
          asset_name: libbytes_arm64.a
          asset_content_type: text/plain
      
      - name: Upload compiled file (x86_64) to Release Page
        uses: actions/upload-release-asset@v1
        with:
          upload_utl: ${{ steps.create_release.outputs.upload_url }}
          asset_path: lib/libytes_x86_64.a
          asset_name: libbytes_x86_64.a
          asset_content_type: text/plain
