name: release

on:
  pull_request:
    branches: [ "main" ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build library
        run: make library
      
      - name: Upload library
        uses: actions/upload-artifact@v3
        with:
          name: libbytes.a
          path: lib/libbytes.a
      
      - name: Upload header
        uses: actions/upload-artifact@v3
        with:
          name: bytes.h
          path: src/bytes.h